// This file is generated by Firebase Genkit.
// Do not edit this file as changes may be overwritten.

'use server';

/**
 * @fileOverview A flow that answers phone call questions from farmers in their local language.
 *
 * - answerPhoneCallQuestion - A function that handles the question answering process.
 * - AnswerPhoneCallQuestionInput - The input type for the answerPhoneCallQuestion function.
 * - AnswerPhoneCallQuestionOutput - The return type for the answerPhoneCallQuestion function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';
import wav from 'wav';

const AnswerPhoneCallQuestionInputSchema = z.object({
  question: z.string().describe('The question asked by the farmer.'),
  language: z.string().describe('The language in which the answer should be provided.'),
});
export type AnswerPhoneCallQuestionInput = z.infer<typeof AnswerPhoneCallQuestionInputSchema>;

const AnswerPhoneCallQuestionOutputSchema = z.object({
  answerAudio: z.string().describe('The audio data of the answer in WAV format as a data URI.'),
});
export type AnswerPhoneCallQuestionOutput = z.infer<typeof AnswerPhoneCallQuestionOutputSchema>;

export async function answerPhoneCallQuestion(input: AnswerPhoneCallQuestionInput): Promise<AnswerPhoneCallQuestionOutput> {
  return answerPhoneCallQuestionFlow(input);
}

const prompt = ai.definePrompt({
  name: 'answerPhoneCallQuestionPrompt',
  input: {schema: AnswerPhoneCallQuestionInputSchema},
  prompt: `You are an AI assistant helping farmers by answering their questions about crops, market prices, government schemes, and weather in their local language.

  Question: {{{question}}}

  Please provide a concise and helpful answer in {{{language}}}. When mentioning currency, use the Indian Rupee symbol (₹). Then, convert the answer to audio using the Text-to-Speech model.
  `,
});

const answerPhoneCallQuestionFlow = ai.defineFlow(
  {
    name: 'answerPhoneCallQuestionFlow',
    inputSchema: AnswerPhoneCallQuestionInputSchema,
    outputSchema: AnswerPhoneCallQuestionOutputSchema,
  },
  async input => {
    const {text} = await prompt(input);

    const {media} = await ai.generate({
      model: 'googleai/gemini-2.5-flash-preview-tts',
      config: {
        responseModalities: ['AUDIO'],
        speechConfig: {
          voiceConfig: {
            prebuiltVoiceConfig: {voiceName: 'Algenib'},
          },
        },
      },
      prompt: text!,
    });

    if (!media) {
      throw new Error('no media returned');
    }

    const audioBuffer = Buffer.from(
      media.url.substring(media.url.indexOf(',') + 1),
      'base64'
    );

    const answerAudio = 'data:audio/wav;base64,' + (await toWav(audioBuffer));

    return {answerAudio};
  }
);

async function toWav(
  pcmData: Buffer,
  channels = 1,
  rate = 24000,
  sampleWidth = 2
): Promise<string> {
  return new Promise((resolve, reject) => {
    const writer = new wav.Writer({
      channels,
      sampleRate: rate,
      bitDepth: sampleWidth * 8,
    });

    let bufs = [] as any[];
    writer.on('error', reject);
    writer.on('data', function (d) {
      bufs.push(d);
    });
    writer.on('end', function () {
      resolve(Buffer.concat(bufs).toString('base64'));
    });

    writer.write(pcmData);
    writer.end();
  });
}
